### ISSUE TITLE
Missing commit and tag for 1.0.1

### ISSUE THREAD

**Issue by jonasmalacofilho** [bheisler/cargo-criterion#22]
Hi,

I just noticed that there's no matching tag for the 1.0.1 release, and that at least one commit (where you bumped the version number and updated the changelog) is missing.

---

`cargo-criterion-1.0.1/.cargo_vcs_info.json`:

```json
{
  "git": {
    "sha1": "c18ad626d6f9e33028f7e3e32e10658cd3ab7d30"
  }
}
```

**Comment by bheisler** [comment]
Hey, good catch, thanks! My bad, the tags should be fixed now.
