### ISSUE TITLE
Criterion.toml vs criterion.toml

### ISSUE THREAD

**Issue by Lemmih** [bheisler/cargo-criterion#35]
Hi, the user's guide states the configuration file is named `criterion.toml` but `cargo-criterion` actually looks for `Criterion.toml`.

I think using the lowercase filename makes the most sense. Would you accept a PR addressing this?

**Comment by bheisler** [comment]
I would accept such a PR. You should now have access to this repository as well (Note for future reference: @Lemmih has volunteered to help out with Criterion-rs maintenance) so you should be able to make the change.

Considering that some folks may already have Criterion.toml files though, perhaps it makes more sense to look for both to avoid breaking existing configurations.

**Comment by Lemmih** [comment]
Yeah, no need to break existing configurations. I'll write the PR.
