### ISSUE TITLE
[Feature request] Tagging and comparing benchmarks

### ISSUE THREAD

**Issue by sigaloid** [bheisler/cargo-criterion#50]
I find myself trying to analyze the exact changes that improve the code change. It's very troublesome to make a change, see it doesn't improve speeds or worsens them, then have to revert to HEAD to start a benchmark again (otherwise, any next change will be compared to the immediately previous one, which might have made it worse, which means reverting would have FIXED the issue but returned it to the HEAD state, leading me to falsely believe I improved speed). 

It might be helpful to have a way to tag a benchmark like so: `cargo criterion --name head`

Then, each subsequent change can be compared to it with: `cargo criterion --compare-to head` (rather than the immediately previous test)

**Comment by Eh2406** [comment]
You may want to look at [baselines](https://bheisler.github.io/criterion.rs/book/user_guide/command_line_options.html#baselines)

**Comment by sigaloid** [comment]
Oops, thank you kindly :smile:
